### PR TITLE
[Fix] Left panel should display no parser message. Fix #1740

### LINKED ISSUE #1740: Left panel blank for countries without parsers
image

The div inviting people to contribute by adding new parsers has disappeared

(same problem on mobile app)
cc @ovbm

### PR DESCRIPTION
**Pull request by ewoken**
Should we remove "hr" from display ? 

PS: it is my first contribution, be indulgent. ;-)

### CODE REVIEW

**Comment by systemcatch** [comment]
Hi @ewoken, thanks for the contribution. Can you build the map locally (https://github.com/tmrowco/electricitymap-contrib#running-locally) so we can see how this looks in a screenshot.

**Comment by systemcatch** [comment]
Fantastic, that looks to be working great. I'm not sure what you mean by margin above message & timeslider though. Maybe try making the changes on your local machine as a demonstration.

**Comment by corradio** [comment]
@ovbm can you review?

File: web/src/components/countrytable.js [hunk 1]
```diff
@@ -625,7 +625,13 @@ CountryTable.prototype.electricityMixMode = function(arg) {
 };
 
 CountryTable.prototype.showNoParserMessageIf = function(condition) {
-  const allChildrenSelector = 'p,.country-table-header-inner,.country-show-emissions-wrap,.country-panel-wrap,.country-history';
+  const allChildrenSelector = `
+    p,.country-table-header-inner,
+    .country-show-emissions-wrap,
+    .country-panel-wrap .bysource,
+    .country-table-container,
+    .country-history
```
Comment (ovbm) [inline web/src/components/countrytable.js]:
```suggestion
    .country-history,
    .zone-time-slider, 
    hr
```

**Comment by ewoken** [comment]
capture d ecran 2019-01-24 a 11 37 14screenshot_2019-01-24 emissions co2 de la consommation electrique en temps reel
As you suggested me, I've added a margin-bottom in the desktop case. I also added a margin-top for mobile in order to separate social-buttons from text.
